const PDFDocument = require('pdfkit');
const Prescription = require('../models/Prescription');
const Invoice = require('../models/Invoice');
const MedicalReport = require('../models/MedicalReport');

exports.downloadPrescription = async (req, res, next) => {
  try {
    const presc = await Prescription.findById(req.params.id)
      .populate({ path: 'patient', select: 'name email phone gender dateOfBirth' })
      .populate({ path: 'doctor', select: 'name email' });
    if (!presc) return res.status(404).json({ success: false, message: 'Prescription not found' });

    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=prescription-${presc._id}.pdf`);
    doc.pipe(res);

    doc.fontSize(20).font('Helvetica-Bold').text('Smart Hospital', { align: 'center' });
    doc.fontSize(10).font('Helvetica').fillColor('#666').text('123 Healthcare Ave, Medical District', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(16).font('Helvetica-Bold').fillColor('#0f4c81').text('Prescription', { align: 'center' });
    doc.moveDown();

    doc.fontSize(10).font('Helvetica').fillColor('#333');
    doc.text(`Patient: ${presc.patient.name} (${presc.patient.gender || 'N/A'})`);
    if (presc.patient.dateOfBirth) doc.text(`DOB: ${new Date(presc.patient.dateOfBirth).toLocaleDateString()}`);
    doc.text(`Doctor: Dr. ${presc.doctor.name}`);
    doc.text(`Date: ${new Date(presc.createdAt).toLocaleDateString()}`);
    if (presc.diagnosis) doc.text(`Diagnosis: ${presc.diagnosis}`);
    doc.moveDown();

    doc.fontSize(12).font('Helvetica-Bold').fillColor('#0f4c81').text('Medicines Prescribed');
    doc.moveDown(0.3);

    const tableTop = doc.y;
    doc.fontSize(9).font('Helvetica-Bold').fillColor('#fff');
    doc.roundedRect(40, tableTop, 515, 18, 4).fill('#0f4c81');
    doc.fillColor('#fff');
    doc.text('Medicine', 50, tableTop + 4, { width: 120 });
    doc.text('Dosage', 180, tableTop + 4, { width: 80 });
    doc.text('Frequency', 270, tableTop + 4, { width: 90 });
    doc.text('Duration', 370, tableTop + 4, { width: 70 });
    doc.text('Notes', 450, tableTop + 4, { width: 100 });

    let y = tableTop + 22;
    doc.fontSize(9).font('Helvetica').fillColor('#333');
    for (const m of presc.medicines) {
      if (y > 720) { doc.addPage(); y = 40; }
      doc.text(m.name, 50, y, { width: 120 });
      doc.text(m.dosage || '-', 180, y, { width: 80 });
      doc.text(m.frequency || '-', 270, y, { width: 90 });
      doc.text(m.duration || '-', 370, y, { width: 70 });
      doc.text(m.notes || '-', 450, y, { width: 100 });
      y += 20;
      doc.moveTo(40, y).lineTo(555, y).strokeColor('#eee').stroke();
      y += 4;
    }

    if (presc.notes) {
      doc.moveDown(2);
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#0f4c81').text('Additional Notes');
      doc.fontSize(9).font('Helvetica').fillColor('#333').text(presc.notes);
    }

    doc.footer = doc.footer || {};
    doc.fontSize(8).fillColor('#999').text('Generated by Smart Hospital System', 40, 800, { align: 'center' });
    doc.end();
  } catch (err) { next(err); }
};

exports.downloadInvoice = async (req, res, next) => {
  try {
    const invoice = await Invoice.findById(req.params.id)
      .populate({ path: 'patient', select: 'name email phone address' });
    if (!invoice) return res.status(404).json({ success: false, message: 'Invoice not found' });

    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=invoice-${invoice.invoiceNumber}.pdf`);
    doc.pipe(res);

    doc.fontSize(20).font('Helvetica-Bold').text('Smart Hospital', { align: 'center' });
    doc.fontSize(10).font('Helvetica').fillColor('#666').text('123 Healthcare Ave, Medical District', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(16).font('Helvetica-Bold').fillColor('#0f4c81').text('Invoice', { align: 'center' });
    doc.moveDown();

    doc.fontSize(10).font('Helvetica').fillColor('#333');
    doc.text(`Invoice #: ${invoice.invoiceNumber}`);
    doc.text(`Date: ${new Date(invoice.createdAt).toLocaleDateString()}`);
    doc.text(`Patient: ${invoice.patient.name}`);
    doc.text(`Email: ${invoice.patient.email}`);
    doc.text(`Status: ${invoice.status.toUpperCase()}`);
    if (invoice.paidAt) doc.text(`Paid On: ${new Date(invoice.paidAt).toLocaleDateString()}`);
    if (invoice.paymentMethod) doc.text(`Payment Method: ${invoice.paymentMethod}`);
    doc.moveDown();

    const tableTop = doc.y;
    doc.fontSize(9).font('Helvetica-Bold').fillColor('#fff');
    doc.roundedRect(40, tableTop, 515, 18, 4).fill('#0f4c81');
    doc.fillColor('#fff');
    doc.text('Description', 50, tableTop + 4, { width: 350 });
    doc.text('Amount', 450, tableTop + 4, { width: 100, align: 'right' });

    let y = tableTop + 22;
    doc.fontSize(9).font('Helvetica').fillColor('#333');
    for (const item of invoice.items) {
      doc.text(item.description, 50, y, { width: 350 });
      doc.text(`₹${item.amount}`, 450, y, { width: 100, align: 'right' });
      y += 20;
      doc.moveTo(40, y).lineTo(555, y).strokeColor('#eee').stroke();
      y += 4;
    }

    doc.moveDown();
    doc.fontSize(11).font('Helvetica-Bold');
    doc.text(`Subtotal: ₹${invoice.subtotal}`, { align: 'right' });
    if (invoice.tax > 0) doc.text(`Tax: ₹${invoice.tax}`, { align: 'right' });
    doc.fillColor('#0f4c81').text(`Total: ₹${invoice.total}`, { align: 'right' });

    doc.fontSize(8).fillColor('#999').text('Generated by Smart Hospital System', 40, 800, { align: 'center' });
    doc.end();
  } catch (err) { next(err); }
};

exports.downloadReport = async (req, res, next) => {
  try {
    const report = await MedicalReport.findById(req.params.id)
      .populate({ path: 'patient', select: 'name email phone gender' })
      .populate({ path: 'doctor', select: 'name' });
    if (!report) return res.status(404).json({ success: false, message: 'Report not found' });

    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=report-${report._id}.pdf`);
    doc.pipe(res);

    doc.fontSize(20).font('Helvetica-Bold').text('Smart Hospital', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(16).font('Helvetica-Bold').fillColor('#0f4c81').text('Medical Report', { align: 'center' });
    doc.moveDown();

    doc.fontSize(10).font('Helvetica').fillColor('#333');
    doc.text(`Patient: ${report.patient.name}`);
    doc.text(`Gender: ${report.patient.gender || 'N/A'}`);
    doc.text(`Doctor: Dr. ${report.doctor.name}`);
    doc.text(`Date: ${new Date(report.createdAt).toLocaleDateString()}`);
    doc.text(`Report Type: ${report.reportType || 'General'}`);
    doc.moveDown();

    doc.fontSize(14).font('Helvetica-Bold').fillColor('#0f4c81').text(report.title);
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').fillColor('#333').text(report.description || 'No description provided.');
    doc.moveDown();

    if (report.fileUrl) {
      doc.fontSize(10).font('Helvetica').fillColor('#666').text('Note: Attached file available separately.', { align: 'center' });
    }

    doc.fontSize(8).fillColor('#999').text('Generated by Smart Hospital System', 40, 800, { align: 'center' });
    doc.end();
  } catch (err) { next(err); }
};
